version: '3.8'

services:
  app:
    build:
      context: .
    container_name: web_app
    ports:
      - "33333:33333"
    volumes:
      - ./app:/usr/src/app
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql+mysqlconnector://root:rootpassword@mysql-container:3306/devops
    depends_on:
      - mysql-container

  mysql-container:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: devops
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d

volumes:
  db_data:




